pool:
  name: 'Self-Hosted-On-Azure'
steps:
- script: |
    k6 version
  displayName: Check if k6 is installed

- script: |
    k6 run loadtests/local.js
  displayName: Run k6 load test within Azure Pipelines
